# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Set-Infinite
version:      0.5307
version_from: lib/Set/Infinite.pm
installdirs:  site
requires:
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
